let indexRouter = require("./routes/index");
let getUserRouter = require("./routes/GET/user");
let postUserRouter = require("./routes/POST/user");
let productsRouter = require("./routes/GET/products");
let productRouter = require("./routes/GET/product");
let productPostRouter = require("./routes/POST/product");
let getMyProductsRouter = require("./routes/GET/myProducts");
let putProductRouter = require("./routes/PUT/product");
let getMessagesRouter = require("./routes/GET/messages");
let postMessageRouter = require("./routes/POST/message");
let deleteProductRouter = require("./routes/DELETE/product");
let myMessages = require("./routes/GET/myMessages");
let sentMessages = require("./routes/GET/sentMessages");
module.exports = (app) => {
  app.use("/", indexRouter);
  app.use("/get/user", getUserRouter);
  app.use("/post/user", postUserRouter);
  // app.use("/get/test", testRouter);
  app.use("/get/products", productsRouter);
  app.use("/get/product", productRouter);
  app.use("/post/product", productPostRouter);
  app.use("/get/myproducts", getMyProductsRouter);
  app.use("/put/product", putProductRouter);
  app.use("/get/messages", getMessagesRouter);
  app.use("/post/message", postMessageRouter);
  app.use("/delete/product", deleteProductRouter);
  app.use("/get/myMessages", myMessages);
  app.use("/get/sentMessages", sentMessages);
};
